name: genmol
channels:
  - pytorch
  - anaconda
  - nvidia
dependencies:
  - cuda-nvcc=12.1
  - pip=23.3.1
  - python=3.10
  - pytorch-cuda=12.1
  - pip:
    - torch==2.6.0
    - datasets==2.18.0
    - hydra-core==1.3.2
    - lightning==2.5.1
    - omegaconf==2.3.0
    - pandas==2.1.0
    - numpy==1.26.4
    - transformers==4.52.4
    - wandb==0.13.5
    - safe-mol
    - PyTDC==0.4.1
    - easydict
    - openbabel-wheel
    - bionemo-moco
